@startuml
class PlacementManager {
    + Initialize(_levelEditor:LevelEditor) : void
    + OnUpdate() : void
    + ChangeTileType(_tileType:int) : void
    + ToggleBulldozing() : void
}
enum PlacingType {
    None,
    PlacingTiles,
    Bulldozing,
    SwitchEditing,
}
MonoBehaviour <|-- PlacementManager
PlacementManager +-- PlacingType
@enduml
